name: test_application
description: "Test Application"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  cupertino_icons: ^1.0.8

  flutter:
    sdk: flutter

  flutter_bloc: ^9.1.0
  freezed: ^2.4.3
  freezed_annotation: ^2.4.4
  get_it: ^8.0.3
  hive_flutter: ^1.1.0
  injectable: ^2.5.0
  solid_lints: ^0.2.3

dev_dependencies:
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0

  flutter_test:
    sdk: flutter

  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
